language: scala

matrix:
  include:
  - scala: 2.12.4
    jdk: oraclejdk8

scala:
  - 2.11.11

jdk:
  - oraclejdk7
  - oraclejdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.coursier
